# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3873335d1e1cf9420120ec992a8fdf823e622b42dab2f09cf2b57aa501c690174e8209ccede947aa997532e66ce57768b47bc75f80b4eb35cc1200b15621a38

test:
  secret_key_base: 41198d1ac6e7cca6ffb7c932c677c80eb89d6e516933ed969e28ca5d02e5e03296c6ae19b2001be1b1200e824290ed25df0d2001d7f447df47cce8ff7d671f16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
