#!/bin/bash

# how to use properly guard to monitor file outsite the current project dir:
#   https://github.com/guard/guard/wiki/Correctly-using-the---watchdir-option
# export BUNDLE_GEMFILE=/Users/ben/pro/fantagrabber/movies/Gemfile
#cd /Users/ben/pro/fantagrabber/rails/movies/local.movie.daemon
cd /usr/local/bin/local.movie.daemon
bundle exec guard -w /Users/ben/Downloads/torrents/ -i &
